[https://www.pivotaltracker.com/story/show/152454553 ]This pull request combines features of all stories I have done this week that has enabled me successfully finish challenge two.
EuniceGatehi/Yummy_Recipes pull request #3
Opened 2017-10-31 22:52 UTC by EuniceGatehi

*What does this PR do?*
- Creates classes, objects and methods recipes and their categories to achieve CRUD operations
- Includes comments and docstrings to code for good coding practice
- Implements the technical feedback received from my LFA's(both for week 1 and 2)
- Obtains badges for build passing[![Build Status](https://travis-ci.org/EuniceGatehi/Yummy_Recipes.svg?branch=developchallengetwo)](https://travis-ci.org/EuniceGatehi/Yummy_Recipes) and coveralls [![Coverage Status](https://coveralls.io/repos/github/EuniceGatehi/Yummy_Recipes/badge.svg?branch=developchallengetwo)](https://coveralls.io/github/EuniceGatehi/Yummy_Recipes?branch=developchallengetwo) through Travis integration
- Deploys app to Heroku
*Description of Task to be completed?*
As indicated in the challenge 2 expectations:
- Setup unit testing libraries and ensure minimal tests written, to practice Test-Driven Development.
- Integrate TravisCI for Continuous Integration in your repository (with ReadMe badge).
- Integrate test coverage reporting (e.g. Coveralls) with a badge in the ReadMe.
- Obtain CI badges (e.g. from Code Climate and Coveralls) and add to ReadMe.
- Integrate the UI templates developed in challenge 1 into your Flask application and make them accessible when you run your app. 
- Develop all required features including their user interfaces. Use OOP and no database (data should be lost when the server is restarted).
- Create a pull request to your develop branch and request two of your friends to review it.
- Deploy your Flask application to Heroku.
*How should this be manually tested?*
For the CRUD operations, run https://yummyflask.herokuapp.com/ to see if all features work correctly
For the readme badges, on my developchallengetwo branch, navigate to the README.md file and view the badges
*What are the relevant pivotal tracker stories?*
[#152454553]https://www.pivotaltracker.com/story/show/152454553
[#152062326]https://www.pivotaltracker.com/story/show/152062326
[#152181931]https://www.pivotaltracker.com/story/show/152181931
[#152181934]https://www.pivotaltracker.com/story/show/152181934
*Screenshots (if appropriate)*
Images for the Travis and Coveralls reports
![image](https://user-images.githubusercontent.com/18480397/32251826-ca22e79e-bea3-11e7-9bec-45dbb2cad123.png)
![image](https://user-images.githubusercontent.com/18480397/32251919-2bd394f2-bea4-11e7-9736-80c0f84d334d.png)
Screenshot for my Heroku app as it appears when you click this link
https://yummyflask.herokuapp.com/
![image](https://user-images.githubusercontent.com/18480397/32252319-e9975fa4-bea5-11e7-9d40-e0f5a9baac4f.png)

2017-11-01 06:53 UTC, Sylvance commented
Looks alright. Coverage is good too.

2017-11-01 08:54 UTC, jonathankamau requested changes
Make sure you have a new line at the end of your files

2017-11-01 08:56 UTC, jonathankamau commented on README.md
> +and voila!you can now use the application.
I do not see the procedure to run tests for your application

2017-11-01 08:56 UTC, jonathankamau commented on app/__init__.py
> +
why this space?

2017-11-01 08:57 UTC, jonathankamau commented on app/recipecategories.py
> +
why this space?

2017-11-01 09:00 UTC, jonathankamau commented on app/recipes.py
> +
why this space?

2017-11-01 09:01 UTC, jonathankamau commented on app/recipes.py
> +
why this space?

2017-11-01 09:13 UTC, jonathankamau reviewed
Why are your bootstrap css and html files on this PR? Your PR for challenge 1 should have contained these files so that once you merge them, the following PR's you create will not have these files. I expected to see only files for challenge 2 on this PR.

2017-11-01 09:23 UTC, jonathankamau commented on app/recipecategories.py
> +            recipe_dict = {
`recipe_dict`??? why not have it as `recipe_details`

2017-11-02 07:06 UTC, jonathankamau commented on app/recipes.py
> +                        edit_dict = {
`edit_dict` :flushed:

2018-03-20 09:15 UTC, merged